#!/usr/bin/env python3
"""Validate and embed the prepared atlas for the offline single-file distribution."""
import base64
import struct
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def validate_atlas(raw):
    if raw[:8] != b'\x89PNG\r\n\x1a\n' or raw[12:16] != b'IHDR' or len(raw) < 33:
        raise ValueError('Building atlas is not a valid PNG; run assets/prepare_building_art.py.')
    width, height, depth, color = struct.unpack('>IIBB', raw[16:26])
    if width != 1254 or height != 1254 or depth != 8 or color != 6:
        raise ValueError('Building atlas must be the prepared 1254px RGBA PNG, not the RGB/checkerboard master.')


def main():
    source = ROOT / 'assets/building/warm-settlement-atlas.png'
    target = ROOT / 'src/building_art_data.js'
    raw = source.read_bytes()
    validate_atlas(raw)
    encoded = base64.b64encode(raw).decode('ascii')
    target.write_text(
        '// Generated by assets/build_building_art.py; do not edit.\n'
        'window.APH=window.APH||{};\nAPH.BUILD_ART_DATA="data:image/png;base64,' + encoded + '";\n',
        encoding='utf-8',
    )
    print(f'Embedded {source.name}: {source.stat().st_size // 1024} KB')


if __name__ == '__main__':
    main()
